// content/contractChecklist.js — text for the downloadable "Renovation contract checklist and sample clauses" PDF.
// General information only. It is NOT the CaseTrust standard contract and not legal advice; it deliberately
// contains no fee amounts, percentages, deadlines or statutory rights. Re-check before republishing.

export const CONTRACT_CHECKLIST = {
  title: 'Renovation contract checklist and sample clauses',
  subtitle: 'What a renovation contract should say, in plain language',
  notice: [
    'This is a checklist and a set of sample wording, written by Layered for homeowners in Singapore. It is not the CaseTrust standard contract, not a legal document and not legal advice.',
    'For CaseTrust accreditation and any standard renovation contract that the Consumers Association of Singapore (CASE) publishes, check the CASE website. For a large or complicated project, or any dispute, ask a lawyer to review your contract.',
    'Use the sample clauses to see whether your own contract covers the same ground. Fill the blanks from your quotation and your discussions. Do not sign a contract with blank spaces.',
  ],
  sections: [
    { h: '1. The parties',
      check: ['The contractor or design firm\'s full registered company name, registration number and address', 'The name of the person signing for the firm, and their role', 'Your full name and the address of the property', 'The company name on the contract matches the name on the bank account you will pay'],
      clause: 'This agreement is made on ____ between ______________________ (Company registration no. ____________), "the Contractor", and ______________________ (NRIC/passport no. kept private), "the Owner", for works at ______________________________ (the "Property").' },
    { h: '2. Scope of work',
      check: ['Every room and area to be worked on, listed one by one', 'Each item with quantity, size and finish (for example carpentry foot runs, tile size, paint brand)', 'What is included in the price and what is expressly excluded', 'The quotation and drawings are attached and signed, and the contract refers to them'],
      clause: 'The Contractor shall carry out the works described in the attached quotation no. ____ dated ____ and drawings no. ____ (together, "the Works"). Anything not listed in those documents is not part of the Works unless agreed in writing under clause 6.' },
    { h: '3. Price and GST',
      check: ['The total contract price, and whether it includes GST', 'The GST rate used, and the firm\'s GST registration number if it is GST-registered', 'A list of exclusions (appliances, furniture, curtains, permit fees, and anything else)', 'Whether prices are fixed or can change, and in what circumstances'],
      clause: 'The contract price is S$ ________ [including / excluding] GST. GST, where applicable, is charged at the rate in force and shown separately on each invoice. The price is fixed except for variations agreed under clause 6.' },
    { h: '4. Payment schedule',
      check: ['Each payment tied to a completed stage, not just a date', 'The amount or percentage and the trigger for every stage', 'Payment to the company\'s bank account or by cheque to the company only, with a receipt every time', 'A final balance held until the walkthrough and defect list are done'],
      clause: 'The Owner shall pay the contract price in the stages below, each payable within ____ days of the Contractor completing the stage and issuing an invoice.',
      table: [['Stage', 'What must be finished before payment', 'Amount (S$)'], ['Deposit on signing', '', ''], ['Stage 2', '', ''], ['Stage 3', '', ''], ['Stage 4', '', ''], ['Final balance', 'Walkthrough done and agreed defects fixed', '']] },
    { h: '5. Timeline and delays',
      check: ['Start date and expected completion date', 'What counts as a reasonable extension (for example approvals outside the Contractor\'s control)', 'What happens if the Contractor is late, and what happens if the Owner delays access or decisions', 'How the Contractor will tell you about delays, and when'],
      clause: 'The Works shall start on ____ and be completed by ____. The completion date may be extended only for reasons agreed in writing. If the Contractor is late for reasons within its control, the parties shall agree remedies as follows: ______________________.' },
    { h: '6. Variations (changes to the work)',
      check: ['Every change is written, priced and signed before the work is done', 'How variations are priced', 'How variations affect the completion date and the payment schedule', 'Verbal changes are not binding on either side'],
      clause: 'No change to the Works shall be carried out unless a written variation order stating the change, its price and any effect on the completion date has been signed by both parties.' },
    { h: '7. Materials and specification',
      check: ['Key materials listed by brand, colour code and grade where it matters', 'Replacement of a material needs your written consent', 'Who supplies what (some items you may buy yourself)', 'Samples approved before ordering'],
      clause: 'The Contractor shall use the materials listed in the quotation. A substitute of equal or better quality may be used only with the Owner\'s written consent.' },
    { h: '8. Permits, approvals and licensed work',
      check: ['Who applies for permits and notifies HDB, the management corporation or other authorities', 'Who pays for them', 'Electrical work is done by a person licensed to do it, and water-service work by a licensed plumber (check the current requirements with the EMA and PUB)', 'The firm meets any HDB requirements for the works (check how to verify on HDB\'s site)'],
      clause: 'The Contractor shall obtain all permits and approvals needed for the Works and shall ensure that regulated work is carried out by persons licensed to do it. Permit costs are borne by ______________.' },
    { h: '9. Supervision, site rules and insurance',
      check: ['The named project manager or supervisor and how often they visit', 'How the site, lifts and common areas are protected', 'Who is responsible for damage to your property or the neighbours\' property', 'What insurance the firm carries, and whether you can see it'],
      clause: 'The Contractor\'s project manager is ______________ (phone ____________). The Contractor shall protect common areas and shall be responsible for damage caused by its workers and subcontractors.' },
    { h: '10. Defects, warranty and handover',
      check: ['A walkthrough at the end with a written defect list', 'A date by which agreed defects are fixed', 'How long the warranty lasts, what it covers and how to claim', 'What you can hold back until defects are fixed'],
      clause: 'On completion the parties shall inspect the Works and record defects in writing. The Contractor shall fix recorded defects within ____ days and shall remedy defects arising from its workmanship or materials for ____ months after handover.' },
    { h: '11. Ending the contract and disputes',
      check: ['What happens if either side ends the contract early, including how work already done is valued and paid', 'How a dispute is raised and who the first contact is', 'Where you can get help (for example CASE, or a lawyer)', 'Whether the contract is governed by Singapore law'],
      clause: 'Either party who wishes to end this contract shall give written notice stating the reason. Work properly carried out before the end date shall be valued and paid for as agreed in writing, or as decided under clause ____ if the parties do not agree.' },
  ],
  signature: 'Signed for the Contractor: ______________________   Date: ________        Signed by the Owner: ______________________   Date: ________',
  before: [
    'Read every page, including the small print.',
    'Make sure everything said in meetings is also in writing.',
    'Do not sign blank or incomplete pages.',
    'Keep a signed copy of the contract, the quotation and the drawings.',
    'Pay only what the schedule requires, to the company, and keep every receipt.',
    'Check the firm\'s registration and any accreditation yourself on the official lookups.',
  ],
};
